// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"go-farms/internal/modules/farm/repositories"
	"go-farms/internal/modules/farm/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeFarmService(db *gorm.DB) service.FarmServiceInterface {
	farmRepositoryInterface := repository.GetFarmRepository(db)
	farmServiceInterface := service.GetFarmService(farmRepositoryInterface)
	return farmServiceInterface
}

// wire.go:

var FarmServiceSet = wire.NewSet(repository.GetFarmRepository, service.GetFarmService)
